# Homework 1 Part 2: Github Action to execute make and make tests
name: 'make'
on: [push]
jobs:
  make:
    runs-on: ubuntu-latest

    steps:
      - name: execute make and make test
        run: make && make test