# Homework 1 Part 2: Github Action to execute make and make tests
name: 'make'
on: [push]
jobs:
  make:
    runs-on: ubuntu-latest

    steps:
      - name: clone
        run: git clone https://github.com/NYUAppSec/assignment-1-milind-daftari.git

      - name: execute make
        run: make giftcardreader

      - name: execute make test
        run: make test