# Homework 1 Part 1: Setting up Your Environment
name: 'Hello World'
on: [push]
jobs:
  hello_world:
    runs-on: windows-latest

    steps:
      - name: Echo Hello World
        run: echo "Hello World"